<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class PagesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('pages')->delete();

        \DB::table('pages')->insert(array (
            0 =>
            array (
                'id' => 1,
                'page_id' => NULL,
                'type' => '1',
                'slug' => '{"az":"","en":"","ru":""}',
                'name' => '{"az":"Ana s\\u0259hif\\u0259","en":"Main Page","ru":"\\u0413\\u043b\\u0430\\u0432\\u043d\\u0430\\u044f \\u0441\\u0442\\u0440\\u0430\\u043d\\u0438\\u0446\\u0430"}',
                'published' => 1,
                'shown_in_menu' => 0,
                'created_at' => '2022-06-21 11:27:03',
                'updated_at' => '2022-06-21 11:27:03',
                'deleted_at' => NULL,
                'show_in_burger' => 0,
                'show_in_header' => 0,
                'order' => 1,
            ),
            1 =>
            array (
                'id' => 3,
                'page_id' => 1,
                'type' => '3',
                'slug' => '{"az":"news","en":"newsen","ru":"newsru"}',
                'name' => '{"az":"news","en":"news","ru":"news"}',
                'published' => 0,
                'shown_in_menu' => 1,
                'created_at' => '2022-06-21 14:21:07',
                'updated_at' => '2022-06-28 00:52:11',
                'deleted_at' => NULL,
                'show_in_burger' => 0,
                'show_in_header' => 0,
                'order' => 1,
            ),
            2 =>
            array (
                'id' => 7,
                'page_id' => 1,
                'type' => '4',
                'slug' => '{"az":"media","en":"media","ru":"media"}',
                'name' => '{"az":"Media","en":"Media","ru":"Media"}',
                'published' => 1,
                'shown_in_menu' => 1,
                'created_at' => '2022-06-24 17:34:28',
                'updated_at' => '2022-06-28 03:29:55',
                'deleted_at' => NULL,
                'show_in_burger' => 1,
                'show_in_header' => 0,
                'order' => 6,
            ),
            3 =>
            array (
                'id' => 9,
                'page_id' => 7,
                'type' => '3',
                'slug' => '{"az":"xeberler","en":"xeberler","ru":"xeberler"}',
                'name' => '{"az":"X\\u0259b\\u0259rl\\u0259r","en":"X\\u0259b\\u0259rl\\u0259r","ru":"X\\u0259b\\u0259rl\\u0259r"}',
                'published' => 1,
                'shown_in_menu' => 1,
                'created_at' => '2022-06-24 17:44:20',
                'updated_at' => '2022-06-28 03:06:14',
                'deleted_at' => NULL,
                'show_in_burger' => 1,
                'show_in_header' => 1,
                'order' => 1,
            ),
            4 =>
            array (
                'id' => 10,
                'page_id' => 7,
                'type' => '5',
                'slug' => '{"az":"elanlar","en":"elanlar","ru":"elanlar"}',
                'name' => '{"az":"Elanlar","en":"Elanlar","ru":"Elanlar"}',
                'published' => 1,
                'shown_in_menu' => 1,
                'created_at' => '2022-06-26 12:17:00',
                'updated_at' => '2022-06-28 03:06:19',
                'deleted_at' => NULL,
                'show_in_burger' => 1,
                'show_in_header' => 1,
                'order' => 1,
            ),
            5 =>
            array (
                'id' => 11,
                'page_id' => 7,
                'type' => '6',
                'slug' => '{"az":"multimedia","en":"multimedia","ru":"multimedia"}',
                'name' => '{"az":"Multimedia","en":"Multimedia","ru":"Multimedia"}',
                'published' => 1,
                'shown_in_menu' => 1,
                'created_at' => '2022-06-26 12:33:03',
                'updated_at' => '2022-06-28 03:06:23',
                'deleted_at' => NULL,
                'show_in_burger' => 1,
                'show_in_header' => 1,
                'order' => 1,
            ),
            6 =>
            array (
                'id' => 12,
                'page_id' => 1,
                'type' => '4',
                'slug' => '{"az":"haqqimizda","en":"haqqimizda","ru":"haqqimizda"}',
                'name' => '{"az":"Haqq\\u0131m\\u0131zda","en":"Haqq\\u0131m\\u0131zda","ru":"Haqq\\u0131m\\u0131zda"}',
                'published' => 1,
                'shown_in_menu' => 1,
                'created_at' => '2022-06-26 14:14:51',
                'updated_at' => '2022-06-28 02:16:01',
                'deleted_at' => NULL,
                'show_in_burger' => 1,
                'show_in_header' => 1,
                'order' => 1,
            ),
            7 =>
            array (
                'id' => 14,
                'page_id' => 12,
                'type' => '8',
                'slug' => '{"az":"umumi-melumat","en":"umumi-melumat","ru":"umumi-melumat"}',
                'name' => '{"az":"\\u00dcmumi m\\u0259lumat","en":"\\u00dcmumi m\\u0259lumat","ru":"\\u00dcmumi m\\u0259lumat"}',
                'published' => 1,
                'shown_in_menu' => 1,
                'created_at' => '2022-06-26 14:31:17',
                'updated_at' => '2022-06-28 03:09:21',
                'deleted_at' => NULL,
                'show_in_burger' => 1,
                'show_in_header' => 1,
                'order' => 1,
            ),
            8 =>
            array (
                'id' => 15,
                'page_id' => 12,
                'type' => '9',
                'slug' => '{"az":"rehberlik","en":"rehberlik","ru":"rehberlik"}',
                'name' => '{"az":"R\\u0259hb\\u0259rlik","en":"R\\u0259hb\\u0259rlik","ru":"R\\u0259hb\\u0259rlik"}',
                'published' => 0,
                'shown_in_menu' => 1,
                'created_at' => '2022-06-26 15:06:12',
                'updated_at' => '2022-06-29 11:03:20',
                'deleted_at' => NULL,
                'show_in_burger' => 1,
                'show_in_header' => 1,
                'order' => 1,
            ),
            9 =>
            array (
                'id' => 16,
                'page_id' => 12,
                'type' => '10',
                'slug' => '{"az":"struktur","en":"struktur","ru":"struktur"}',
                'name' => '{"az":"Struktur","en":"Struktur","ru":"Struktur"}',
                'published' => 1,
                'shown_in_menu' => 1,
                'created_at' => '2022-06-26 15:42:59',
                'updated_at' => '2022-06-29 11:06:46',
                'deleted_at' => NULL,
                'show_in_burger' => 1,
                'show_in_header' => 1,
                'order' => 3,
            ),
            10 =>
            array (
                'id' => 17,
                'page_id' => 12,
                'type' => '11',
                'slug' => '{"az":"maliyye-hesabatlari","en":"maliyye-hesabatlari","ru":"maliyye-hesabatlari"}',
                'name' => '{"az":"Maliyy\\u0259 hesabatlar\\u0131","en":"Maliyy\\u0259 hesabatlar\\u0131","ru":"Maliyy\\u0259 hesabatlar\\u0131"}',
                'published' => 1,
                'shown_in_menu' => 1,
                'created_at' => '2022-06-26 17:53:48',
                'updated_at' => '2022-06-29 11:07:30',
                'deleted_at' => NULL,
                'show_in_burger' => 1,
                'show_in_header' => 1,
                'order' => 4,
            ),
            11 =>
            array (
                'id' => 18,
                'page_id' => 12,
                'type' => '12',
                'slug' => '{"az":"pese-tehsil-merkezi","en":"pese-tehsil-merkezi","ru":"pese-tehsil-merkezi"}',
                'name' => '{"az":"Pe\\u015f\\u0259 T\\u0259hsil M\\u0259rk\\u0259zi","en":"Pe\\u015f\\u0259 T\\u0259hsil M\\u0259rk\\u0259zi","ru":"Pe\\u015f\\u0259 T\\u0259hsil M\\u0259rk\\u0259zi"}',
                'published' => 1,
                'shown_in_menu' => 1,
                'created_at' => '2022-06-26 19:09:56',
                'updated_at' => '2022-06-29 11:08:00',
                'deleted_at' => NULL,
                'show_in_burger' => 1,
                'show_in_header' => 1,
                'order' => 6,
            ),
            12 =>
            array (
                'id' => 19,
                'page_id' => 1,
                'type' => '4',
                'slug' => '{"az":"qanunvericilik","en":"qanunvericilik","ru":"qanunvericilik"}',
                'name' => '{"az":"Qanunvericilik","en":"Qanunvericilik","ru":"Qanunvericilik"}',
                'published' => 1,
                'shown_in_menu' => 1,
                'created_at' => '2022-06-26 19:32:28',
                'updated_at' => '2022-06-28 02:31:55',
                'deleted_at' => NULL,
                'show_in_burger' => 1,
                'show_in_header' => 1,
                'order' => 2,
            ),
            13 =>
            array (
                'id' => 20,
                'page_id' => 19,
                'type' => '13',
                'slug' => '{"az":"qanunlar","en":"qanunlar","ru":"qanunlar"}',
                'name' => '{"az":"Qanunlar","en":"Qanunlar","ru":"Qanunlar"}',
                'published' => 1,
                'shown_in_menu' => 1,
                'created_at' => '2022-06-26 19:40:14',
                'updated_at' => '2022-06-28 03:00:14',
                'deleted_at' => NULL,
                'show_in_burger' => 1,
                'show_in_header' => 1,
                'order' => 1,
            ),
            14 =>
            array (
                'id' => 21,
                'page_id' => 19,
                'type' => '13',
                'slug' => '{"az":"fermanlar-ve-serencamlar","en":"fermanlar-ve-serencamlar","ru":"fermanlar-ve-serencamlar"}',
                'name' => '{"az":"F\\u0259rmanlar v\\u0259 s\\u0259r\\u0259ncamlar","en":"F\\u0259rmanlar v\\u0259 s\\u0259r\\u0259ncamlar","ru":"F\\u0259rmanlar v\\u0259 s\\u0259r\\u0259ncamlar"}',
                'published' => 1,
                'shown_in_menu' => 1,
                'created_at' => '2022-06-26 20:08:47',
                'updated_at' => '2022-06-28 03:00:42',
                'deleted_at' => NULL,
                'show_in_burger' => 1,
                'show_in_header' => 1,
                'order' => 1,
            ),
            15 =>
            array (
                'id' => 22,
                'page_id' => 19,
                'type' => '13',
                'slug' => '{"az":"esasnameler","en":"esasnameler","ru":"esasnameler"}',
                'name' => '{"az":"\\u018fsasnam\\u0259l\\u0259r","en":"\\u018fsasnam\\u0259l\\u0259r","ru":"\\u018fsasnam\\u0259l\\u0259r"}',
                'published' => 1,
                'shown_in_menu' => 1,
                'created_at' => '2022-06-26 20:10:20',
                'updated_at' => '2022-06-28 03:01:08',
                'deleted_at' => NULL,
                'show_in_burger' => 1,
                'show_in_header' => 1,
                'order' => 1,
            ),
            16 =>
            array (
                'id' => 23,
                'page_id' => 19,
                'type' => '13',
                'slug' => '{"az":"qerarlar","en":"qerarlar","ru":"qerarlar"}',
                'name' => '{"az":"Q\\u0259rarlar","en":"Q\\u0259rarlar","ru":"Q\\u0259rarlar"}',
                'published' => 1,
                'shown_in_menu' => 1,
                'created_at' => '2022-06-26 20:11:40',
                'updated_at' => '2022-06-28 03:01:30',
                'deleted_at' => NULL,
                'show_in_burger' => 1,
                'show_in_header' => 1,
                'order' => 1,
            ),
            17 =>
            array (
                'id' => 24,
                'page_id' => 19,
                'type' => '13',
                'slug' => '{"az":"qaydalar-ve-formalar","en":"qaydalar-ve-formalar","ru":"qaydalar-ve-formalar"}',
                'name' => '{"az":"Qaydalar v\\u0259 formalar","en":"Qaydalar v\\u0259 formalar","ru":"Qaydalar v\\u0259 formalar"}',
                'published' => 1,
                'shown_in_menu' => 1,
                'created_at' => '2022-06-26 20:12:59',
                'updated_at' => '2022-06-28 03:01:48',
                'deleted_at' => NULL,
                'show_in_burger' => 1,
                'show_in_header' => 1,
                'order' => 1,
            ),
            18 =>
            array (
                'id' => 25,
                'page_id' => 1,
                'type' => '4',
                'slug' => '{"az":"ustunlukler","en":"ustunlukler","ru":"ustunlukler"}',
                'name' => '{"az":"\\u00dcst\\u00fcnl\\u00fckl\\u0259r","en":"\\u00dcst\\u00fcnl\\u00fckl\\u0259r","ru":"\\u00dcst\\u00fcnl\\u00fckl\\u0259r"}',
                'published' => 1,
                'shown_in_menu' => 1,
                'created_at' => '2022-06-26 20:17:26',
                'updated_at' => '2022-06-28 02:34:36',
                'deleted_at' => NULL,
                'show_in_burger' => 0,
                'show_in_header' => 1,
                'order' => 4,
            ),
            19 =>
            array (
                'id' => 26,
                'page_id' => 25,
                'type' => '2',
                'slug' => '{"az":"infrastruktur","en":"infrastruktur","ru":"infrastruktur"}',
                'name' => '{"az":"\\u0130nfrastruktur","en":"\\u0130nfrastruktur","ru":"\\u0130nfrastruktur"}',
                'published' => 1,
                'shown_in_menu' => 1,
                'created_at' => '2022-06-26 20:20:47',
                'updated_at' => '2022-06-28 03:11:54',
                'deleted_at' => NULL,
                'show_in_burger' => 0,
                'show_in_header' => 1,
                'order' => 1,
            ),
            20 =>
            array (
                'id' => 27,
                'page_id' => 25,
                'type' => '2',
                'slug' => '{"az":"vergi-ve-gomruk-guzestleri","en":"vergi-ve-gomruk-guzestleri","ru":"vergi-ve-gomruk-guzestleri"}',
                'name' => '{"az":"Vergi v\\u0259 g\\u00f6mr\\u00fck g\\u00fcz\\u0259\\u015ftl\\u0259ri","en":"Vergi v\\u0259 g\\u00f6mr\\u00fck g\\u00fcz\\u0259\\u015ftl\\u0259ri","ru":"Vergi v\\u0259 g\\u00f6mr\\u00fck g\\u00fcz\\u0259\\u015ftl\\u0259ri"}',
                'published' => 1,
                'shown_in_menu' => 1,
                'created_at' => '2022-06-26 20:26:25',
                'updated_at' => '2022-06-28 03:12:01',
                'deleted_at' => NULL,
                'show_in_burger' => 0,
                'show_in_header' => 1,
                'order' => 1,
            ),
            21 =>
            array (
                'id' => 28,
                'page_id' => 25,
                'type' => '2',
                'slug' => '{"az":"logistik-imkanlar","en":"logistik-imkanlar","ru":"logistik-imkanlar"}',
                'name' => '{"az":"Logistik imkanlar","en":"Logistik imkanlar","ru":"Logistik imkanlar"}',
                'published' => 1,
                'shown_in_menu' => 1,
                'created_at' => '2022-06-26 20:32:26',
                'updated_at' => '2022-06-28 03:12:07',
                'deleted_at' => NULL,
                'show_in_burger' => 0,
                'show_in_header' => 1,
                'order' => 1,
            ),
            22 =>
            array (
                'id' => 29,
                'page_id' => 25,
                'type' => '2',
                'slug' => '{"az":"azad-ticaret-imkanlari","en":"azad-ticaret-imkanlari","ru":"azad-ticaret-imkanlari"}',
                'name' => '{"az":"Azad ticar\\u0259t imkanlar\\u0131","en":"Azad ticar\\u0259t imkanlar\\u0131","ru":"Azad ticar\\u0259t imkanlar\\u0131"}',
                'published' => 1,
                'shown_in_menu' => 1,
                'created_at' => '2022-06-26 20:34:20',
                'updated_at' => '2022-06-28 03:12:12',
                'deleted_at' => NULL,
                'show_in_burger' => 0,
                'show_in_header' => 1,
                'order' => 1,
            ),
            23 =>
            array (
                'id' => 30,
                'page_id' => 25,
                'type' => '2',
                'slug' => '{"az":"bir-pencere","en":"bir-pencere","ru":"bir-pencere"}',
                'name' => '{"az":"Bir p\\u0259nc\\u0259r\\u0259","en":"Bir p\\u0259nc\\u0259r\\u0259","ru":"Bir p\\u0259nc\\u0259r\\u0259"}',
                'published' => 1,
                'shown_in_menu' => 1,
                'created_at' => '2022-06-26 20:36:06',
                'updated_at' => '2022-06-28 03:12:17',
                'deleted_at' => NULL,
                'show_in_burger' => 0,
                'show_in_header' => 1,
                'order' => 1,
            ),
            24 =>
            array (
                'id' => 31,
                'page_id' => 25,
                'type' => '2',
                'slug' => '{"az":"tedqiqat-ve-inkisaf","en":"tedqiqat-ve-inkisaf","ru":"tedqiqat-ve-inkisaf"}',
                'name' => '{"az":"T\\u0259dqiqat v\\u0259 inki\\u015faf","en":"T\\u0259dqiqat v\\u0259 inki\\u015faf","ru":"T\\u0259dqiqat v\\u0259 inki\\u015faf"}',
                'published' => 1,
                'shown_in_menu' => 1,
                'created_at' => '2022-06-26 20:38:37',
                'updated_at' => '2022-06-28 03:12:22',
                'deleted_at' => NULL,
                'show_in_burger' => 0,
                'show_in_header' => 1,
                'order' => 1,
            ),
            25 =>
            array (
                'id' => 32,
                'page_id' => 1,
                'type' => '4',
                'slug' => '{"az":"muracietler","en":"muracietler","ru":"muracietler"}',
                'name' => '{"az":"M\\u00fcraci\\u0259tl\\u0259r","en":"M\\u00fcraci\\u0259tl\\u0259r","ru":"M\\u00fcraci\\u0259tl\\u0259r"}',
                'published' => 1,
                'shown_in_menu' => 1,
                'created_at' => '2022-06-26 21:13:34',
                'updated_at' => '2022-06-28 02:34:50',
                'deleted_at' => NULL,
                'show_in_burger' => 1,
                'show_in_header' => 1,
                'order' => 5,
            ),
            26 =>
            array (
                'id' => 33,
                'page_id' => 32,
                'type' => '7',
                'slug' => '{"az":"tez-tez-verilen-suallar","en":"tez-tez-verilen-suallar","ru":"tez-tez-verilen-suallar"}',
                'name' => '{"az":"Tez-tez veril\\u0259n suallar","en":"Tez-tez veril\\u0259n suallar","ru":"Tez-tez veril\\u0259n suallar"}',
                'published' => 1,
                'shown_in_menu' => 1,
                'created_at' => '2022-06-26 21:14:11',
                'updated_at' => '2022-06-28 03:04:05',
                'deleted_at' => NULL,
                'show_in_burger' => 1,
                'show_in_header' => 1,
                'order' => 1,
            ),
            27 =>
            array (
                'id' => 34,
                'page_id' => 32,
                'type' => '14',
                'slug' => '{"az":"qebul-qrafiki","en":"qebul-qrafiki","ru":"qebul-qrafiki"}',
                'name' => '{"az":"Q\\u0259bul qrafiki","en":"Q\\u0259bul qrafiki","ru":"Q\\u0259bul qrafiki"}',
                'published' => 1,
                'shown_in_menu' => 1,
                'created_at' => '2022-06-26 21:35:59',
                'updated_at' => '2022-06-28 03:04:39',
                'deleted_at' => NULL,
                'show_in_burger' => 1,
                'show_in_header' => 1,
                'order' => 1,
            ),
            28 =>
            array (
                'id' => 35,
                'page_id' => 32,
                'type' => '15',
                'slug' => '{"az":"elaqe","en":"elaqe","ru":"elaqe"}',
                'name' => '{"az":"\\u018flaq\\u0259","en":"\\u018flaq\\u0259","ru":"\\u018flaq\\u0259"}',
                'published' => 1,
                'shown_in_menu' => 1,
                'created_at' => '2022-06-26 22:17:27',
                'updated_at' => '2022-06-28 03:05:20',
                'deleted_at' => NULL,
                'show_in_burger' => 1,
                'show_in_header' => 1,
                'order' => 1,
            ),
            29 =>
            array (
                'id' => 36,
                'page_id' => 32,
                'type' => '16',
                'slug' => '{"az":"sikayet-teklif-ve-muraciet","en":"sikayet-teklif-ve-muraciet","ru":"sikayet-teklif-ve-muraciet"}',
                'name' => '{"az":"\\u015eikay\\u0259t, t\\u0259klif v\\u0259 m\\u00fcraci\\u0259t","en":"\\u015eikay\\u0259t, t\\u0259klif v\\u0259 m\\u00fcraci\\u0259t","ru":"\\u015eikay\\u0259t, t\\u0259klif v\\u0259 m\\u00fcraci\\u0259t"}',
                'published' => 1,
                'shown_in_menu' => 1,
                'created_at' => '2022-06-26 23:11:04',
                'updated_at' => '2022-06-28 03:05:25',
                'deleted_at' => NULL,
                'show_in_burger' => 1,
                'show_in_header' => 1,
                'order' => 1,
            ),
            30 =>
            array (
                'id' => 37,
                'page_id' => 1,
                'type' => '4',
                'slug' => '{"az":"iqtisadi-zonalar","en":"iqtisadi-zonalar","ru":"iqtisadi-zonalar"}',
                'name' => '{"az":"\\u0130qtisadi zonalar","en":"\\u0130qtisadi zonalar","ru":"\\u0130qtisadi zonalar"}',
                'published' => 1,
                'shown_in_menu' => 1,
                'created_at' => '2022-06-27 02:21:26',
                'updated_at' => '2022-06-28 02:34:16',
                'deleted_at' => NULL,
                'show_in_burger' => 1,
                'show_in_header' => 1,
                'order' => 3,
            ),
            31 =>
            array (
                'id' => 38,
                'page_id' => 37,
                'type' => '17',
                'slug' => '{"az":"senaye-parklari","en":"senaye-parklari","ru":"senaye-parklari"}',
                'name' => '{"az":"S\\u0259naye parklar\\u0131","en":"S\\u0259naye parklar\\u0131","ru":"S\\u0259naye parklar\\u0131"}',
                'published' => 1,
                'shown_in_menu' => 1,
                'created_at' => '2022-06-27 03:31:19',
                'updated_at' => '2022-06-28 03:02:41',
                'deleted_at' => NULL,
                'show_in_burger' => 1,
                'show_in_header' => 1,
                'order' => 1,
            ),
            32 =>
            array (
                'id' => 39,
                'page_id' => 38,
                'type' => '18',
                'slug' => '{"az":"sumqayit-senaye-parki","en":"sumqayit-senaye-parki","ru":"sumqayit-senaye-parki"}',
                'name' => '{"az":"Sumqay\\u0131t s\\u0259naye park\\u0131","en":"Sumqay\\u0131t s\\u0259naye park\\u0131","ru":"Sumqay\\u0131t s\\u0259naye park\\u0131"}',
                'published' => 1,
                'shown_in_menu' => 1,
                'created_at' => '2022-06-27 03:35:37',
                'updated_at' => '2022-06-27 03:37:39',
                'deleted_at' => NULL,
                'show_in_burger' => 0,
                'show_in_header' => 0,
                'order' => 1,
            ),
            33 =>
            array (
                'id' => 40,
                'page_id' => 38,
                'type' => '18',
                'slug' => '{"az":"baki-senaye-parki","en":"baki-senaye-parki","ru":"baki-senaye-parki"}',
                'name' => '{"az":"Bak\\u0131 s\\u0259naye park\\u0131","en":"Bak\\u0131 s\\u0259naye park\\u0131","ru":"Bak\\u0131 s\\u0259naye park\\u0131"}',
                'published' => 1,
                'shown_in_menu' => 1,
                'created_at' => '2022-06-27 03:36:12',
                'updated_at' => '2022-06-27 03:37:41',
                'deleted_at' => NULL,
                'show_in_burger' => 0,
                'show_in_header' => 0,
                'order' => 1,
            ),
            34 =>
            array (
                'id' => 41,
                'page_id' => 37,
                'type' => '2',
                'slug' => '{"az":"senaye-mehelleleri","en":"senaye-mehelleleri","ru":"senaye-mehelleleri"}',
                'name' => '{"az":"S\\u0259naye m\\u0259h\\u0259ll\\u0259l\\u0259ri","en":"S\\u0259naye m\\u0259h\\u0259ll\\u0259l\\u0259ri","ru":"S\\u0259naye m\\u0259h\\u0259ll\\u0259l\\u0259ri"}',
                'published' => 1,
                'shown_in_menu' => 1,
                'created_at' => '2022-06-27 22:25:57',
                'updated_at' => '2022-06-28 03:03:02',
                'deleted_at' => NULL,
                'show_in_burger' => 1,
                'show_in_header' => 1,
                'order' => 1,
            ),
            35 =>
            array (
                'id' => 42,
                'page_id' => 37,
                'type' => '17',
                'slug' => '{"az":"aqro-parklar","en":"aqro-parklar","ru":"aqro-parklar"}',
                'name' => '{"az":"Aqro parklar","en":"Aqro parklar","ru":"Aqro parklar"}',
                'published' => 1,
                'shown_in_menu' => 1,
                'created_at' => '2022-06-27 22:27:16',
                'updated_at' => '2022-06-28 03:03:26',
                'deleted_at' => NULL,
                'show_in_burger' => 1,
                'show_in_header' => 1,
                'order' => 1,
            ),
            36 =>
            array (
                'id' => 43,
                'page_id' => 42,
                'type' => '19',
                'slug' => '{"az":"sabirabad-aqro-parki","en":"sabirabad-aqro-parki","ru":"sabirabad-aqro-parki"}',
                'name' => '{"az":"Sabirabad aqro park\\u0131","en":"Sabirabad aqro park\\u0131","ru":"Sabirabad aqro park\\u0131"}',
                'published' => 1,
                'shown_in_menu' => 1,
                'created_at' => '2022-06-27 22:37:46',
                'updated_at' => '2022-06-28 02:29:37',
                'deleted_at' => NULL,
                'show_in_burger' => 0,
                'show_in_header' => 0,
                'order' => 1,
            ),

            38 =>
            array (
                'id' => 46,
                'page_id' => 12,
                'type' => '4',
                'slug' => '{"az":"forum","en":"forum","ru":"forum"}',
                'name' => '{"az":"Forum","en":"Forum","ru":"Forum"}',
                'published' => 1,
                'shown_in_menu' => 0,
                'created_at' => '2022-06-28 10:25:48',
                'updated_at' => '2022-06-28 10:25:52',
                'deleted_at' => NULL,
                'show_in_burger' => 0,
                'show_in_header' => 0,
                'order' => 1,
            ),
            37 =>
                array (
                    'id' => 45,
                    'page_id' => 46,
                    'type' => '20',
                    'slug' => '{"az":"rezident-ol","en":"rezident-ol","ru":"rezident-ol"}',
                    'name' => '{"az":"Rezident ol","en":"Rezident ol","ru":"Rezident ol"}',
                    'published' => 1,
                    'shown_in_menu' => 0,
                    'created_at' => '2022-06-28 10:23:00',
                    'updated_at' => '2022-06-28 10:26:05',
                    'deleted_at' => NULL,
                    'show_in_burger' => 0,
                    'show_in_header' => 0,
                    'order' => 1,
                ),
            39 =>
            array (
                'id' => 47,
                'page_id' => 12,
                'type' => '21',
                'slug' => '{"az":"rehberlik","en":"rehberlik","ru":"rehberlik"}',
                'name' => '{"az":"R\\u0259hb\\u0259rlik","en":"R\\u0259hb\\u0259rlik","ru":"R\\u0259hb\\u0259rlik"}',
                'published' => 1,
                'shown_in_menu' => 1,
                'created_at' => '2022-06-29 11:02:52',
                'updated_at' => '2022-06-29 11:05:55',
                'deleted_at' => NULL,
                'show_in_burger' => 1,
                'show_in_header' => 1,
                'order' => 2,
            ),
        ));


    }
}
